version: "3"

services:
  wisenetwave:
    image: wisenetwave
    build:
      context: .
    #privileged: true
    restart: unless-stopped
    volumes:
      - ./runtime/config:/root/.config
      - ./runtime/var:/opt/hanwha/mediaserver/var
      - ./config:/opt/hanwha/mediaserver/etc
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - 7001:7001

  # client:
  #   image: wisenetclient
  #   build:
  #     context: ./client
  #   volumes:
  #     - /dev/shm:/dev/shm
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #   environment:
  #     - DISPLAY
